### ISSUE TITLE
Questions re: display and flex-wrap

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/responsive-image-section#1]
Markbot is expecting `display: inline-block` and `flex-wrap: wrap` but I'm not sure where and why. I can only think of `<img>` as it's the only element that moves on the page but this (esp. `flex-wrap: wrap`) almost forces me to think backwards (from larger to smaller screen instead of 'mobile first'). Maybe I'm having a brain freeze moment.

Also, a general question: why do we assign some properties to `<html>`  and some to `<body>` , for example, font to html but margin to body? How about color and background-color? I always find myself questioning whether I should be applying these to html or body tag.

Thanks! 

@thomasjbradley

**Comment by thomasjbradley** [comment]
**Re: `flex-wrap` —**

I’m using it on, essentially, here:
https://github.com/C-G-G/responsive-image-section/blob/gh-pages/index.html#L11

The elements are always flex & wrapped, just we change their widths in media queries to make the layout change.

---

**Re: `inline-block` —**

I have this on the `a` tag, so I can make it look like a button & properly apply padding.
https://github.com/C-G-G/responsive-image-section/blob/gh-pages/index.html#L19

**Comment by thomasjbradley** [comment]
> Also, a general question: why do we assign some properties to <html> and some to <body> , for example, font to html but margin to body? How about color and background-color? I always find myself questioning whether I should be applying these to html or body tag.

I generally don’t apply anything to `body`. With the exception of `margin: 0` because the body tag has a margin on it from browser defaults—and I want to get rid of it.

Everything else that applies to the *whole page* I assign to the `html` tag.

(Sometimes, if you’re doing fancy scroll effects, or other weird layout things you’ll need more properties on `body`.)

**Comment by C-G-G** [comment]
Just to clarify your first point, do you apply `display: flex` and `flex-wrap: wrap` to `section` early on before media queries and change widths of `div` and `img` later in media queries? I guess you also change wrap to nowrap so `img` moves up next to div at larger screens. There is something I'm still not getting and trying to understand what it is.  

@thomasjbradley

**Comment by thomasjbradley** [comment]
Yep, that’s exactly correct.

**Comment by C-G-G** [comment]
Thanks so much! I revised my code accordingly and things look good on my end but Markbot is still not happy finding it visually too different from screenshots (see attached; one on the left is how I see on my browser). Could this be a glitch? Is this something I should investigate more or just pass? Want to make sure that I'm not doing or skipping something important. 

<img width="836" alt="responsive-image-section-screenshot-2021Jun27" src="https://user-images.githubusercontent.com/16348315/123555786-e17a1b00-d755-11eb-9d64-195fa71e2dff.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
Does look a little bit glitchy—yeah. Looking in the browser it looks okay to me.
